---
always_allow_html: yes
output:
  word_document:
    reference_docx: template.docx
  html_document:
    df_print: paged
---

# 2 危害识别
&emsp;&emsp;铅是一种金属元素，原子序数82，原子量207.2。铅为带蓝色的银白色重金属，它有毒性，是一种有延伸性的主族金属。熔点327.502 ℃，沸点1740 ℃，密度11.3437 g/cm3，比热容0.13 kJ/（kg·K），硬度1.5，原子体积18.17 cm3 /mol，质地柔软，抗张强度小。金属铅在空气中受到氧、水和二氧化碳作用，其表面会很快氧化生成保护薄膜;在加热下，铅能很快与氧、硫、卤素化合;铅与冷盐酸、冷硫酸几乎不起作用，能与热或浓盐酸、硫酸反应;铅与稀硝酸反应，但与浓硝酸不反应;铅能缓慢溶于强碱性溶液。铅主要用于制造铅蓄电池;铅合金可用于铸铅字，做焊锡;铅还用来制造放射性辐射、X射线的防护设备;铅及其化合物对人体有较大毒性，并可在人体内积累。铅被用作建筑材料，用在硫酸铅电池中，用作枪弹和炮弹，焊、奖杯和一些合金中也含铅。铅还可以做成开花弹（又名达姆弹）。铅（Pb）是一种在自然界分布广泛的重金属污染物，饮用水、各类农作物和经济作物等均可不同程度地受到铅污染。铅可在人体内长期蓄积，半衰期长达 14 年。人体铅暴露的主要途径包括空气、饮用水、食物等，而通过手-口途径摄入含铅的灰尘、土壤或接触含铅的油漆玩具和器皿则是儿童铅暴露的重要途径，对于一些长期服药人群，药物也是不容忽视的重要来源。铅的低浓度长期暴露可影响大脑和神经系统发育，对人体健康最显著的危害是降低儿童的认知能力和智力。  
&emsp;&emsp;铅的数据库不同寻常，因为它包含了大量关于人体剂量-效应关系的数据。这些数据来自对职业暴露群体和普通人群的研究。人类毒性效应包括神经发育效应、诱变性、致癌性、心血管作用、肾脏效应、内分泌系统效应、胃肠道效应、血液学效应、肌肉骨骼效应、生殖效应和发育效应等。大多数这些终点也在实验动物身上进行了研究，这些研究为人类关于作用或行为方式的数据提供支持。发育中的神经系统已被确定为铅的关键靶器官。对细胞系统、动物和人类的基因毒性的研究表明，铅是一种间接的诱变剂。在国际癌症研究机构进行的一项评估中得出结论认为，实验动物有足够的证据表明铅化合物的致癌性，而人类对铅化合物致癌性的证据有限。本章着重于铅的神经发育、肾脏和心血管作用、基因毒性和致癌性，因为这些都是人们关注的潜在终点，无论是由于该作用的性质或敏感性。


## 2.1 吸收


### 2.1.1 口腔接触情况
&emsp;&emsp;摄入铅的胃肠道吸收受生理因素（如年龄、禁食、营养钙和铁状况、怀孕）和颗粒的物理化学特征（大小、溶解度和铅种类）的影响。吸收机制的细节仍待确定。  
&emsp;&emsp;在禁食受试者的放射性示踪剂实验中，根据研究结果，吸收率为37-70%（平均约60%）。从成年人对铅稳定同位素摄取的研究来看，估计平均吸收率为15-20%。儿童对摄入可溶的铅化合物的吸收似乎高于成人，尽管母亲和孩子体内B-Pb稳定同位素特征的变化动力学表明，6至11岁的儿童及其母亲吸收了相似比例的铅。  
&emsp;&emsp;实验动物的研究为胃肠道吸收的年龄依赖提供了额外的证据。口服醋酸铅（每千克饲料中含铅6.37 mg），幼年猴对铅的吸收率为38%，而成年雌性猴为26%。幼鼠通过饮食吸收的铅大约是成年鼠的40到50倍。  
&emsp;&emsp;食物的存在降低了水溶性铅化合物的吸收，据报道，与膳食一起服用时，吸收率从3%到21%不等（平均约8%）。在成人中，禁食受试者摄入水中醋酸铅的示踪剂量约为63%，而随餐食用时仅为3%。报道的禁食成人吸收估计的算术平均值为57%，报道的进食/禁食比例在0.04到0.2之间。  
&emsp;&emsp;儿童对铅的吸收受营养铁状况的影响。低铁摄入量和缺铁状态与B-Pb增加有关。铁缺乏对铅吸收的影响已经通过大鼠的研究提供了证据，表明铁缺乏可能通过增强其与铁载体的结合增加铅的吸收  
&emsp;&emsp;膳食钙的摄入似乎会影响铅的吸收。儿童膳食钙摄入与B-Pb浓度之间存在反比关系，表明缺乏钙的儿童可能比钙充足的儿童吸收更多的铅。钙对铅吸收的影响在成年人中也很明显。在对成年人的实验研究中，当铅与碳酸钙一起摄入时（0.2-1 g碳酸钙），单剂量铅（100-300 g氯化铅）的吸收量比不补充钙摄入时要低。在实验动物模型中，通过膳食钙消耗或服用维生素D来增强铅的吸收。尽管牛奶是钙的主要来源，一个多世纪以来牛奶一直被推荐作为铅毒性的预防剂，但它增加了铅的摄入量。牛奶中的铅盐和铅似乎被不同的机制吸收。乳糖的作用有限，而乳铁蛋白可能会导致吸收的增加。类似的机制可能有助于铅-铁和铅-钙的相互吸收作用，以及铅与其他二价阳离子，如镉、铜、镁和锌等二价阳离子之间的相互作用。


### 2.1.2 吸入暴露
&emsp;&emsp;吸入性含铅颗粒的沉积和吸收受到其大小和溶解度的影响。与密度较低的颗粒物相比，铅烟雾和含铅粉尘的沉积量略有不同，其可呼吸部分的特征是空气动力学直径较低。大于5微米的颗粒沉积在气管和支气管的内衬液上，通过粘液纤毛输送转移到咽部，然后被咽下，可能从胃肠道吸收铅。较小的颗粒可以沉积在呼吸道远端，经细胞外溶解或被肺泡巨噬细胞吞噬后被吸收。  
&emsp;&emsp;在暴露于空气动力学直径小于1 m的含铅颗粒的成年人中，测量了呼吸道的沉积和清除。作为亚微米颗粒吸入的沉积铅高达95%被吸收。


## 2.2 急性毒性
&emsp;&emsp;铅被描述为一种典型的慢性毒药。一次暴露后一般不会观察到对健康的影响，据报告铅盐的口服LD50值大于2,000 mg/kg bw。动物在多次短期口服接触醋酸铅、氯酸铅、硝酸铅、油酸铅、氧化物铅或硫酸铅后观察到的最低致死剂量为300至4000 mg/kg bw。


## 2.3 重复用药剂量和慢性毒性
### 2.3.1 神经毒性和神经发育毒性
&emsp;&emsp;主要针对啮齿动物和非人灵长类动物模型的实验研究证明，长期低水平接触铅会影响学习能力等行为，尤其是发育中的动物。这些影响的程度似乎在很大程度上取决于暴露发生的发育时期。  
&emsp;&emsp;对大鼠和非人灵长类动物的研究已经证明了与B-Pb相关的学习缺陷浓度在100~150 μg/L之间，这个范围与流行病学研究报告的范围相当，其中发现儿童有学习缺陷。  
&emsp;&emsp;逆转或反复学习的缺陷与铅暴露是一致的发现。这些学习障碍似乎是普遍的，已经有跨物种和刺激维度的报道。8只怀孕（妊娠5至8.5周）的松鼠猴产前接触铅，导致母体血液浓度在210 µg/L和790 µg/L之间，结果显示，在血浓度超过400 µg/L时，5至6岁的松鼠猴的行为改变，如后代的学习能力受到影响。在母体B-Pb浓度较低时，对学习能力仍有一定的影响。在出生时给予浓度为320-360 µg/L铅剂量的猴子中，7至8岁时空间辨别逆转任务受损。这是否反映了不同类型学习范式的不同临界接触期尚不清楚。有关铅对不同行为领域的影响的研究，尚未在不同的发育阶段有系统地进行，因此无法确定任何行为缺陷的关键时期。  
&emsp;&emsp;大鼠在不同发育阶段分别饲喂775 mg/kg铅，并对其主动回避学习能力和海马长期增强能力进行测试。当暴露包括产前和产后早期并持续到成年时，这两个过程都受到损害。然而，当出生后16天开始暴露时，学习和海马电位均未受影响。这些结果反映了与成熟的海马相比，发育中的海马更容易出现铅诱导的功能缺陷。  
&emsp;&emsp;许多人类研究将铅相关的认知功能障碍归因于注意力缺陷。在实验研究中，铅暴露的非人类灵长类动物的鉴别逆转缺陷被解释为对无关刺激的注意力分散增加。  
&emsp;&emsp;注意力缺陷多动障碍（ADHD）的临床诊断依赖于三个行为领域：注意力不集中、多动症和冲动。基于临床诊断领域的最近两项研究发现支持这一种可能性，即冲动受铅的影响大于持续注意力，而冲动作为一种行为功能障碍最终可能导致认知障碍。在铅暴露的动物模型中，对多动症的报道并不一致，有增加，减少，没有变化。  
&emsp;&emsp;两组7周龄大鼠分别给予50 mg/L乙酸钠和50 mg/L醋酸铅3个月。眼球功能测试是通过在一个增加角速度的平台上旋转动物，并在突然停止旋转时测量眼球震颤。暴露于铅的动物显示出旋转后眼球震颤减少，这在统计学上与B-Pb和脑铅浓度显著相关，而在用醋酸钠处理的动物中没有观察到这种变化。结果表明，低浓度的铅可能会损害感觉和运动功能，并表明这种测量即使没有铅中毒的临床迹象，也提供了铅的神经毒性作用的筛查工具。  
&emsp;&emsp;5只12到28个月大的猫通过插入下丘脑侧的电极被精确控制的电流刺激。反应措施是掠夺性攻击阈值，即在50%的试验中引起攻击的响应。以50-150 mg/kg/day醋酸铅的剂量混合到猫粮中。为期4到5周。在铅暴露前、中和后的B-Pb浓度分别为<10、210-770和<200 μg/L。五只猫中的三只在接触铅时，掠食性攻击阈值显著下降，五只猫中的四只停止接触铅后，攻击阈值增加（p<0.01）。阈值电流与B-Pb浓度之间存在显著负相关（p<0.002）。这些数据表明，铅暴露可增强猫的掠食性攻击性。    
&emsp;&emsp;主要在暴露于铅下的大鼠和猴子身上进行的行为测试结果表明，表现受损至少部分是分散注意力、无法抑制不当反应以及对不再适当的行为坚持等综合因素的结果。

### 2.3.2 心血管的作用
&emsp;&emsp;许多动物实验表明，血压对铅暴露有双相反应。据报道，长期（3或12个月）低水平铅暴露自发性高血压大鼠（饮用水中醋酸铅为25 mg/L），在3个月时增强了心脏对缺血诱发心律失常的易感性，但在12个月时没有，但对血压没有任何影响。相比之下，这些大鼠的亚慢性（3个月）高水平暴露于铅（饮用水中为250或1000 mg/L）只会导致心脏对心肌缺血引起的心律失常的敏感性略有增强。两种剂量的铅都加速了高血压的发展，而血压正常的大鼠中，高剂量的铅也会导致血压升高。与对照组相比，15至18只断奶大鼠在饮用含铅量为0.1、1.0或5.0 mg/L的饮用水3个月、6个月或1年后，收缩压（sbp）均持续显著升高。这在一项研究中得到证实，10只白化病鼠给予25、50或1000 mg/L的饮用水中的铅。90天后，每组5只大鼠测量血压，其余5只终止对心脏组织进行组织病理学和组织化学研究。动脉血压的增加仅在两个最高剂量的组中有统计学意义。在本研究中，铅导致心房小梁和乳头肌的钙流入增加。该机制与铅改变钙转运过程的能力有关。

### 2.3.3 中毒性肾损害
&emsp;&emsp;慢性铅中毒与近端肾小管上皮细胞中存在特征性的核内包涵体有关。在兔子、大鼠、猴子和狗的肾脏中观察到了铅诱导的包涵体形成。  
&emsp;&emsp;为低钙饮食的雄性 大鼠建立了铅肾病的实验模型。用0.5% （高剂量）和0.01% （低剂量）的醋酸铅在饮用水中浸泡1ー12个月，并与对照组大鼠进行比较。6个月后，用0.5%醋酸铅处理动物，醋酸铅从0.5%降至0.1%，B-Pb的最大值达到1.254±101 μg/L。这些动物12个月时的B-Pb平均为550 μg/L。在铅处理大鼠6个月时，出现局灶性管萎缩和间质纤维化，可达12个月。12个月的肾小球显示出局灶性和节段性硬化症。  
&emsp;&emsp;在第二项研究中，对持续低水平铅暴露的动物进行了12个月的事件进程研究。这些动物在三个月时达到最高B-Pb水平，平均为294±41 μg/L。在1个月和3个月时，GFR显著高于对喂养对照组，但在其他时间点正常。在12个月内，肾脏没有其他病理变化，并出现轻度肾小管萎缩和间质性纤维化。应注意的是，低剂量铅处理动物和高剂量铅处理动物在铅暴露的前3个月里都表现出“超滤”效应。

### 2.3.4基因毒性
&emsp;&emsp;铅的基因毒性研究已经在体内外得到了广泛的应用。在细菌系统中，只有铬酸铅和溴化铅会致突变，但这些测试的活性部分可能分别是铬酸盐或溴化物。在无细胞系统中，质粒DNA中的DNA链断裂有所增加。有人认为，这是由于一个类似芬顿的反应，包括将Pb2+还原到Pb1+或铅氧或过氧化铅复合物。  
&emsp;&emsp;在含有铬酸铅的哺乳动物细胞中进行了多次测试。在这些研究中，不能排除观察到的效应是由铬酸盐引起的。关于醋酸铅诱导染色体畸差，72小时培养的人类白细胞染色体损伤、染色单体断裂和等染色单体断裂的频率明显升高，而48小时培养的人类白细胞染色体畸变的频率明显升高。其他关于硝酸铅和谷氨酸铅的研究大多是阴性的。关于微核的诱导，报道从1.1 μM氯化铅或0.05 μM醋酸铅浓度开始的剂量依赖性增加。诱发姐妹分体交换的阳性和阴性结果均有报告。  
&emsp;&emsp;许多研究表明，醋酸铅和硝酸铅诱导哺乳动物细胞的DNA损伤，对DNA链断裂产生阴性或（大多弱）阳性结果；一项研究发现核DNA中没有8-羟基-2′脱氧鸟苷，其中一项研究提出诱导DNA-蛋白质交联。  
&emsp;&emsp;在体内，使用彗星试验评估雄性大鼠肾脏细胞的DNA损伤。服用铅的大鼠彗星尾长度和姐妹染色单体交换数量增加。当小鼠在饮用水中接触醋酸铅时，在F1和F2代血细胞中彗星尾长度增加，而大鼠血细胞中彗星尾长度没有增加。在一项研究中口服或注射醋酸铅的猴子淋巴细胞中染色体畸变（间隙和片段）和非整倍体频率增加，但在另一项研究中未发现。在一次体内诱变实验中，饮用水中的氯化铅对小鼠显性致死试验没有影响。  
&emsp;&emsp;总之，关于基因毒性的数据表明，铅可能是一种较弱的间接基因毒素。

### 2.3.5致癌性
&emsp;&emsp;在几项研究中，口服醋酸铅已被证明对大鼠肾脏有致癌作用，在雄性和雌性慢性暴露后产生腺瘤和腺癌。与人类的摄入剂量相比，这些研究中的剂量很高。在其中三项研究中，每千克饲料中铅的最低剂量为3或5 mg，在其余的研究中，剂量为500或1000 ppm，相当于成年大鼠约20或40 mg/kg bw/day。在两项适用的研究（即超过两个剂量组）中，显示出剂量-反应关系。在一项研究中，在饲料中给予醋酸铅，使每只大鼠每天摄入3 mg铅，持续两个月，随后每只大鼠每天摄入4 mg铅，持续16个月。大鼠的几个器官出现肿瘤，雄性肾上腺、睾丸和前列腺以及雌性肾上腺肿瘤发病率有统计学意义上的显著增加。在另一项针对雄性和雌性大鼠的研究中，每天口服接触3mg醋酸铅的大鼠与肺、垂体、前列腺、乳腺和肾上腺的肿瘤有关。初孕鼠（每组20只）在妊娠期和哺乳期饮用水中分别注射0、500、750和1000 mg/L的醋酸铅，发现后代出现肾肿瘤。在大多数病例中，肿瘤附近的肾组织表现正常，或只有轻度的老化肾病。一项对金属硫蛋白双基因敲除小鼠的研究表明，这些小鼠比野生型小鼠更容易受到铅诱发的肾癌的影响。野生型小鼠肾脏常见含铅核包涵体，而金属硫蛋白缺失小鼠未见其形成。金属硫蛋白常与这些包涵体的外部有关。因此，金属硫蛋白缺失的小鼠即使长期接触铅，也不会形成肾脏包涵体，这增加了铅的致癌潜力。金属硫蛋白的低产可能使某些个体易于导致致癌性。在两项不同的研究中（每只大鼠铅的剂量为3 mg/day）口服接触醋酸铅后观察到脑胶质瘤。此外，在饲料中添加0.1% 剂量的亚醋酸铅，可诱发大鼠和小鼠的肾癌。在一项研究中，口服醋酸铅的仓鼠不会长肿瘤。在四项单独的研究中，皮下注射磷酸铅或皮下和腹腔联合注射磷酸铅会对大鼠产生肾癌。三项实验表明，口服接触亚醋酸铅可增强雄鼠正乙基-N-羟乙基亚硝胺诱导雄鼠肾癌发生。口服接触硝酸铅增加了雄性大鼠N-亚硝基二甲胺诱导肾肿瘤的发病率，而腹腔注射醋酸铅增加了N-亚硝基二甲胺诱导小鼠肺肿瘤的多发性。  
&emsp;&emsp;总的来说，大量的实验证据表明，各种高剂量的水溶性和不溶性铅化合物可以在啮齿动物的不同部位诱导肿瘤。此外，一项研究表明，微量铅诱导肾病可能发生肾肿瘤。同样值得注意的是，在大鼠口服铅后诱发了脑胶质瘤，这种情况很少是自发的。铅在暴露于各种有机肾致癌物的小鼠中被证明是一种肾肿瘤致癌物/促进剂。由于铅不是一种直接作用的基因毒素，而且在啮齿动物实验中用于诱导肿瘤的剂量比人类的摄入量高，因此EFSA污染小组认为人类通过食物接触铅不太可能代表重大的癌症风险。



# 3 危害特征描述
&emsp;&emsp;由于目前尚无法确定一个可有效保护健康的铅暴露阈值，所以本研究采用暴露限值（Margin of Exposure，MOE）方法对中药材铅暴露的潜在危害进行风险评估，计算公式为: MOE=BMDL01 /Exp。当以成年人心血管效应（收缩压升高） 作为毒性效应终点，其收缩压基准剂量下限值（BMDL01）为每天1.3 μg/kg bw 。   
&emsp;&emsp;食物是人群铅经口暴露的最主要来源，在对中药材的铅暴露水平进行评估时应当考虑膳食来源铅暴露的水平。从保守评估考虑，本报告选择1.3 μg/kg体质量为健康指导值，采用暴露限值（margin of exposure，MOE）方法对铅暴露的潜在危害进行风险评估，计算公式为：MOE＝BMDL0.5/（Exp*h），h为安全因子，本评估报告中将安全因子h设为100。当MOE≥1时，表示该中药摄入人群由铅引起的健康风险较低。反之，当MOE≤1时，表示该中药由砷引起的健康风险较高且需要关注。
