---
always_allow_html: yes
output:
  word_document:
    reference_docx: template.docx
  html_document:
    df_print: paged
---

# 2 危害识别
&emsp;&emsp;铬（Chromium），元素符号 Cr，是一种过渡金属元素，原子序数为 24，原子量为 51.9961。铬是一种广泛分布于环境中的金属，存在于岩石、土壤、火山尘埃和气体中。铬以-2价至+6价的一系列多种氧化态存在，其中三价(Cr^3+^)和六价(Cr^6+^)状态相对稳定且占主导地位。虽然Cr^3+^是一种天然的膳食成分，存在于各种食品和膳食补充剂中，但Cr^6+^最常出现在工业过程中，并且通常作为人为污染的结果存在于饮用水中。在人类饮食暴露水平下，铬的吸收相对较低(<摄入剂量的10%)，并取决于其价态和配体。大多数摄入的Cr^6+^被认为在胃中被还原为Cr^3+^，其生物利用度较差，进入细胞的能力较低。与Cr^3+^不同，Cr^6+^能够穿过细胞膜。Cr^6+^到Cr^3+^的相互转化与风险评估相关，一般认为Cr^6+^的毒性比Cr^3+^的毒性高1,000倍。

## 2.1 吸收、分布、代谢和排泄（ADME）
&emsp;&emsp;据报道，人体对补充铬的吸收效率在0.1%至5.2%之间(Donaldson,Barreras 1966;Anderson等 1983a;Offenbacher等 1986;Gargas等 1994;Kerger等 1996)，并根据摄入的铬络合物而变化(Kerger等 1996;DiSilvestro,Dy 2007)。据估计，食物中Cr^3+^的吸收量在0.4%至2.5%之间(SCF  2003a)，这取决于摄入来源的化学性质和其他膳食成分的存在等因素。据报道，维生素C可增强妇女对铬（以氯化铬的形式）的吸收(Offenbacher 1994)。在大鼠中，植酸盐减少了^51^Cr的吸收，而草酸盐增强了^51^Cr的吸收(Chen等 1973)。  
&emsp;&emsp;吸收后，Cr^3+^与血浆蛋白结合，如转铁蛋白(Hopkins,Schwarz 1964;Sayato等 1980)，只有少量(~ 5%)以未结合的形式存在(Lim等 1983)。然后，铬被运送到肝脏，在那里被隔离；脾脏、软组织和骨骼也会摄取。在人体中，经静脉注射的^51^Cr主要在肝脏和脾脏中积累，但也在软组织和骨骼中积累(Lim等 1983)。铬也被报道存在于皮肤、心脏、大脑、肾脏、胰腺和睾丸中(Schroeder 1968;Sumino等 1975)。  
&emsp;&emsp;尿液是吸收铬的主要排泄途径，少量通过汗液和胆汁排出(Ishihara,Matsushiro 1986)。大多数粪便中的铬由未吸收的铬组成(Donaldson,Barreras 1966;Offenbacher等 1986)。来自欧洲一小群妇女的成熟人乳中的平均铬浓度变化很大，范围为0.14-10.8 μg/L。

## 2.2 动物毒性效应
### 2.2.1 急性毒性
&emsp;&emsp;Cr^3+^作为无机盐或有机复合物口服（灌胃）对大鼠和小鼠均无急性毒性，LD~50~ >2000 mg/kg bw。相反，水溶性Cr^6+^化合物（三氧化铬、铬酸钠、重铬酸钠、重铬酸钾）对大鼠和小鼠均有急性毒性，雄性/雌性大鼠的LD~50~为46 ~ 113 mg/kg bw/d，雄性/雌性小鼠的LD50为135 ~ 175 mg/kg bw。  
&emsp;&emsp;Islam等人(2005年)报告，单次口服给药后，鸡体内氧化铬的近似致死剂量(ALD50)为172 mg/kg bw。  
&emsp;&emsp;金属的毒性机制涉及一系列共同的事件，包括氧化应激和活性氧的产生。Arivarasu等(2008)报道，通过饮用水单次口服100 mg/kg bw重铬酸钾可导致大鼠肠黏膜氧化应激增加（脂质过氧化增加，总SH组减少）。在小鼠中，口服重铬酸钠或钾后，观察到氧化应激的各种迹象以及染色质冷凝和嵴线粒体丢失等细胞凋亡改变(Wang等 2006;Bagchi等 2002;Travacio等 2001)。

### 2.2.2重复剂量毒性  
&emsp;&emsp;Cr^3+^对实验动物的毒性很小（体重下降或体重增加很小）或没有毒性,大鼠亚慢性和长期毒性的相关NOAEL~s~分别为506和286 mg/kg bw/d(所测最高剂量)。  
&emsp;&emsp;反复口服Cr^6+^会导致各种不良反应，例如体重增加（减少）、血液参数和肝脏。多次口服接触Cr^6+^后，氧化应激的迹象（GSH和GSSG水平升高，SOD和CAT活性升高）已被多个研究明确报道(Thompson等 2012;Nudler等 2009)。Bucher(2007)报道了雄性和雌性大鼠在饮水中暴露于1000 mg/L重铬酸钠90天后，肝功能改变（例如胆汁酸浓度升高）和腺胃非肿瘤性病变（局灶性溃疡、再生上皮增生和鳞状上皮化生）增加。  
&emsp;&emsp;在NTP为期90天的毒性研究中，将饮用水中的重铬酸钠以高达1000 mg/L的剂量水平给予大鼠90天，对红细胞（小细胞性贫血）和肝脏造成影响。在所有剂量水平下都记录了影响，因此没有确定NOAEL。最高剂量为1000 mg/L时，对非腺胃粘膜有明显的局部刺激作用（重铬酸钠脱水研究报告，2007）。  
&emsp;&emsp;在某些情况下，已经进行了重复剂量毒性研究，以调查暴露于Cr^6+^后口腔粘膜肿瘤的作用模式。Thompson等人(2012)报道了口服重铬酸钾90天后，十二指肠的组织病理学发现、与氧化状态相关的生化分析以及靶组织（口腔、十二指肠、空肠）中铬含量的增加。  
&emsp;&emsp;Samuel Jawahar等人(2011)报道了通过哺乳对雌性大鼠的生育能力和幼鼠的不利影响。该研究以重复剂量和繁殖/发育筛查相结合的方式进行，重铬酸钾通过饮用水喂给哺乳的母鼠，通过母乳喂给幼鼠。大鼠体重和子宫重均显著下降，血清和子宫中Cr^6+^浓度呈剂量依赖性升高。随着年龄的增长，血清和子宫Cr^6+^水平逐渐下降。青春期开始的时间随剂量的增加而推迟，雌雄期延长。  
&emsp;&emsp;持续接触饮用水中的高浓度六价铬会导致小鼠肠道肿瘤，但不会导致大鼠肠道肿瘤。为了研究这方面的问题，Kopec 等(2012)研究了大鼠和小鼠十二指肠和空肠上皮在接触二水合重铬酸钠 7 天和 90 天后的浓度依赖性基因表达效应。大鼠差异基因表达反应的表型锚定与氧化应激反应基因表达、稳定胃肠粘膜并提供抵御有毒物质物理屏障的细胞生长、免疫反应、DNA 损伤和修饰基因有关。  


### 2.2.3遗传毒性
&emsp;&emsp;数据证实，六价铬(Cr^6+^)在有或没有代谢激活的鼠伤寒沙门氏菌菌株上具有遗传毒性。当三价铬作为醋酸Cr^3+^施用于鼠伤寒沙门氏菌时，没有遗传毒性（关于三醋酸铬的研究报告，2008）。相反，三价铬作为二代半胱氨酸铬(CDNC)给药时对鼠伤寒沙门氏菌TA 98、TA 100、TA 1537菌株具有遗传毒性(Sreejayan等 2010)。  
&emsp;&emsp;据报道，铬通过诱导单倍体酵母菌的信号通路或使生长控制如肿瘤抑制基因失活来抑制主要DNA修复、氧化DNA损伤、解除细胞增殖的调控(Riger等 2011)。  
&emsp;&emsp;在体外哺乳动物染色体畸变试验中，不同浓度的Cr^6+^对有或没有代谢激活的哺乳动物细胞都具有遗传毒性(ECB 2005)。El-Yamani等(2011)报道了用Cr^6+^处理的人淋巴母细胞TK6细胞的DNA损伤（DNA损伤和/或修复）的彗星测定。  
&emsp;&emsp;在小鼠淋巴瘤L5178Y细胞试验中，吡啶甲酸铬具有遗传毒性(Whittaker等 2005)，而在有无代谢激活的中国仓鼠卵巢细胞(CHO-K1)试验中，吡啶甲酸铬没有遗传毒性(Slesinsky等 2005)。在对中国仓鼠卵巢细胞(CHO)进行测试时，三吡啶甲酸铬没有遗传毒性(Coryell等 2006)。  

### 2.2.4生殖毒性
&emsp;&emsp;关于铬对生殖参数影响的研究数量非常有限。  
&emsp;&emsp;Rhodes (2005)报道了Fischer 344大鼠在饲料中添加一水吡啶羧酸铬93天对精子和动情周期的影响。雄性Sprague-Dawley大鼠每天腹腔注射重铬酸钾26天，可使附睾精子数和附性器官重量(Chandra Amar 2010)下降。  
&emsp;&emsp;一份关于重铬酸钾的研究报告(2005)提到了三项在小鼠身上进行的研究，在这些研究中，将试验项目添加到饮用水中会对小鼠的生育能力产生影响。  
&emsp;&emsp;在饮用水中给雄性猴子施用铬酸钾导致精子数量和活力下降(Subramanian等 2006)。处理还抑制了精浆和精子中超氧化物歧化酶和过氧化氢酶的活性，降低了谷胱甘肽水平，增加了H~2~O~2~的产生。同时服用维生素C并在6个月后停用铬治疗均可导致效果逆转。


## 2.3 对人类健康的影响  
&emsp;&emsp;没有设计良好的前瞻性人体研究被确定为口服暴露于总铬，Cr^3+^或Cr^6+^。  
&emsp;&emsp;从少数案例研究中获得的信息非常有限，不适于评估人体口服接触Cr^3+^化合物后的毒性。  
&emsp;&emsp;在意外或故意中毒后，非常高剂量的Cr^6+^对呼吸系统、血液系统、肝脏和肾脏系统以及胃肠道产生急性健康影响，其中急性影响包括腹痛、呕吐、溃疡、出血、坏死和血性腹泻。  
&emsp;&emsp;根据职业研究的证据，国际癌症研究机构将六价铬列为对人类具有致癌性的物质，可导致肺癌、鼻癌和鼻窦癌。有关口服接触的数据有限，没有令人信服的证据表明与包括癌症在内的不良健康影响有关。  
&emsp;&emsp;现有数据不足以评估从食物或水中口服六价铬对发育和生殖系统的毒性以及致敏可能性。


# 3 危害特征描述  
## 3.1 三价铬
&emsp;&emsp;专家小组根据一项长期大鼠研究确定的NOAEL(286 μg/kg bw/d)，采用默认的不确定性因子100来考虑物种差异和人体变异，并采用额外的不确定性因子10来考虑生殖和发育毒性方面缺乏足够数据的情况，得出了Cr^3+^的容许日摄入量为300 μg/kg bw/d。

## 3.2 六价铬
&emsp;&emsp;由于腺瘤-癌序列是公认的胃肠道癌变途径，在保守的方法中，CONTAM小组选择了BMDL~10~，即1.0 mg/kg bw/d的Cr^6+^用于雄性和雌性小鼠的合并腺瘤或小肠癌，作为估计肿瘤变化的MOE的参考点。  
&emsp;&emsp;CONTAM小组通过对实验动物非肿瘤性病变的分析，选择雌性小鼠十二指肠弥漫性上皮增生的最低BMDL~10~值0.11 mg/kg bw/d的Cr^6+^作为估计非肿瘤性病变MOE的参考点。  
&emsp;&emsp;从对大鼠血液学影响的分析中，CONTAM小组选择了最低的BMDL~05~为0.2 mg/kg bw/d来降低雄性大鼠的红细胞压比。该值被用作MOE估计血液毒性作用的参考点。
