---
always_allow_html: yes
output:
  word_document:
    reference_docx: template.docx
  html_document:
    df_print: paged
---

# 2 危害识别
&emsp;&emsp;镉是一种金属元素，原子序数48，原子量112.411。金属镉具有银白色光泽，有韧性和延展性，熔点320.9℃，沸点765℃，密度8.642 g/cm³。镉为稀有元素，在地壳中的含量约为十万分之二，通常富含于硫镉矿、铅锌矿等中。镉在自然界主要以二价无机化合物的形式存在，其囟化物、硝酸盐易溶于水，氢氧化物不溶于水。但镉的碳酸盐、氧化物在人体胃酸环境下溶解性增加。目前在自然界中尚未发现与碳原子共价结合的有机镉化合物。地壳中的镉可通过火山喷发和岩石风化进入人类环境中，而矿山开采和冶炼可人为地使镉大量释放进入环境。镉可广泛用于电镀、肥料、颜料、电池原料及核反应堆等的生产，因此工业废料的排放、农作物施肥等人类生产活动均可显著提高土壤、水和空气中镉的水平，进而造成食品中的镉污染。

### 2.1 急性毒性
&emsp;&emsp;人类单纯通过食物或饮料摄入大量镉时，往往表现为急性胃肠炎症状，但通过职业接触或自杀等原因短时间内暴露高剂量的镉则会造成机体多个脏器和组织损伤，甚至死亡，死亡原因是大量体液丢失、组织水肿和多脏器衰竭。在已观察到的案例中，镉元素经口未观察到效应的水平（NOEL）为 3 mg/人，致死剂量为 350-8900 mg/人。

### 2.2 慢性毒性
&emsp;&emsp;持续给大鼠含有磷酸铝钠（288 mg/kg.bw）或氢氧化铝（302  mg/kg.bw）的饲料28天，未发现与给药相关的毒性效应。每天经口给予比格犬碱性磷酸铝钠(80 mg /kg.bw)，26周后动物出现进食量下降，雄性动物伴有体重和睾丸重量降低及肝脏和肾脏组织病理学改变，其观察到效应的最低剂量（Lowest Observed Effect Level，LOEL）为75－80 mg /kg.bw。大鼠饮用含硝酸铝（104 mg/kg bw）的水28天，脾和肝均出现轻微的组织病理学改变，其未观察到不良作用水平(No observed adverse effect level，NOAEL)为52 mg/kg bw。有研究表明，以硫酸铝给大鼠灌胃21天，在17.2  mg/kg.bw的剂量水平即可引起大鼠肝、肾组织的轻度组织病理学改变，其严重程度与染毒剂量水平呈正相关，且肾切除动物对铝的敏感性高于正常者。


### 2.2.1 肾脏损害
&emsp;&emsp;肾脏是膳食镉暴露造成损害的重要靶器官，其损害特征是镉在近曲肾小管中累积而导致细胞功能异常。肾小管损伤最早的表现是对低分子量蛋白质的重吸收能力下降（表现为分泌增加）和细胞脱落，由此导致尿中的某些生物学指标异常。作为慢性镉暴露的主要靶器官，低分子蛋白如B2M和RBP的排泄增加是镉对肾小管毒性的最早表现。根据美国毒物与疾病登记署（ATSDR）的报道，在这些职业暴露研究中观察到对机体产生副作用的尿镉水平为 1.1-15 ug/g Cr（Cr指尿肌酐）。有关环境镉暴露与肾损伤关系，EFSA使用的肾脏损伤标志物多数以B2M为主，在尿镉水平为 1 μg/g Cr左右时，以B2M为主的肾脏损伤标志物即会有所变化。


### 2.2.2 骨骼损害
&emsp;&emsp;长期镉暴露会导致骨软化和骨质疏松，体检时可发现骨密度下降，因此骨密度是最常用的镉暴露所致早期骨损伤的指标，而骨折是骨质疏松的作用终点。上述病变发生的同时常伴有肾损害。EFSA认为尿镉浓度达到0.5 μg/g.Cr时就可能伴随有骨损伤效应发生，该剂量与引起肾脏损害效应的剂量相近。 心血管损伤：有关膳食镉暴露与心血管疾病发病关系的研究结果并不一致，一些关于镉暴露与人群高血压间关系的研究不支持二者的因果关系。但美国和比利时的研究者发现，高尿镉与心肌梗塞以及一些指示心血管功能异常的生理学指标改变有一定相关性。

### 2.2.3 糖尿病
&emsp;&emsp;美国1项研究表明尿镉水平与空腹血糖升高和糖尿病发生都存在着显著的剂量-反应关系，提示镉可能是导致人类糖尿病和糖尿病前期的一个因素。由于肾损伤会导致尿镉排泌增加。

### 2.2.4 神经毒性
&emsp;&emsp;镉对神经系统的毒性研究资料较少。部分研究显示，慢性镉职业接触者在足以引起肾损伤的暴露剂量下可引起嗅觉功能障碍。也有研究结果显示，镉暴露工人在没有出现明显的中毒性肾损害的情况下，却出现了神经行为的改变。

### 2.2.5 生殖和发育毒性
&emsp;&emsp;镉对生殖系统的毒性作用目前仍无充足证据。国外一项研究发现，出生时头发镉水平与 6 岁时精神运动发育延缓的发生率相关。

### 2.2.6 致癌性
&emsp;&emsp;国际癌症研究机构（IARC）将其归为确定的人类致癌物（I类），但欧盟委员会（EC）却将一些镉化合物归为人类可能致癌物。目前对于膳食镉暴露是否能导致人类癌症仍不明确。

# 3 危害特征描述
&emsp;&emsp;为了获得可靠的剂量-反应关系，JECFA选择了B2M作为最适宜标志物，对近些年来发表的文献进行Meta分析，数据囊括了来自35项研究中近30,000例主要来自亚洲的非职业暴露者。由于镉在肾脏中的生物半衰期长达15年以上，因此只有在机体暴露45-50年后肾镉水平才会达到稳定状态。换言之，只有来自50岁以上个体的尿镉浓度数据才能够科学地反映镉对肾脏的长期效应。对这部分人群资料的Meta分析结果表明，当尿镉高于5.24（可信区间4.94-5.57） μg/g Cr时，随着尿镉水平的升高，B2M的排泄量增加，二者呈正相关。因此，根据单室毒代动力学模型的模拟结果，JECFA确定了与尿镉浓度5.24（可信区间4.94-5.57）μg/g Cr相对应的人群膳食镉暴露水平，采用其第5百分位数的低限值，估计为每天每公斤体重0.8 μg，相当于每月每公斤体重25 μg。 考虑到镉的生物半衰期较长，仅某一天内镉暴露量的多少对长期暴露的影响很小。因此2010年第73次JECFA会议决定将原来镉的健康指导值每周可耐受摄入量（PTWI，7 μg/kg bw，相当于60 kg体重的成人每日镉摄入量为60μg）修改为每月可耐受摄入量（PTMI，25 μg/kg bw，相当于60 kg体重的成人每日摄入量为50 μg）。该健康指导值适用于所有年龄组，包括高暴露人群和有特殊膳食习惯的人群（如，素食者）。